//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BileşenOranı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BileşenOranı()
        {
            this.Ürün = new HashSet<Ürün>();
        }
    
        public int bileşenID { get; set; }
        public Nullable<decimal> pamukOranı { get; set; }
        public Nullable<decimal> polyesterOranı { get; set; }
        public Nullable<decimal> KetenOranı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ürün> Ürün { get; set; }
    }
}
