//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int faturaID { get; set; }
        public Nullable<int> kullanıcıID { get; set; }
        public Nullable<int> toplam { get; set; }
        public Nullable<int> siparişNo { get; set; }
    }
}
