//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICI()
        {
            this.Sipariş = new HashSet<Sipariş>();
            this.Tasarımcı = new HashSet<Tasarımcı>();
        }
    
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public Nullable<int> cinsiyetID { get; set; }
        public int kullanıcıID { get; set; }
        public string şifre { get; set; }
        public int kullanıcıTürüID { get; set; }
    
        public virtual Cinsiyet Cinsiyet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipariş> Sipariş { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasarımcı> Tasarımcı { get; set; }
        public virtual KullanıcıTürü KullanıcıTürü { get; set; }
    }
}
