//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipariş
    {
        public int siparişNo { get; set; }
        public int kullanıcıID { get; set; }
        public int ürünBedenID { get; set; }
        public int tutar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual KULLANICI KULLANICI { get; set; }
        public virtual ÜrünBeden ÜrünBeden { get; set; }
    }
}
