//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasarımcı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasarımcı()
        {
            this.Ürün = new HashSet<Ürün>();
        }
    
        public int tasarımcıID { get; set; }
        public int kullanıcıID { get; set; }
        public Nullable<decimal> kazanç { get; set; }
        public string tasarımcıAdı { get; set; }
    
        public virtual KULLANICI KULLANICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ürün> Ürün { get; set; }
    }
}
