//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ürün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ürün()
        {
            this.ÜrünBeden = new HashSet<ÜrünBeden>();
        }
    
        public int ürünID { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public int ürünTürüID { get; set; }
        public Nullable<int> tasarımcıID { get; set; }
        public Nullable<int> bileşenID { get; set; }
        public string ürünAdı { get; set; }
        public Nullable<int> mankenID { get; set; }
        public string photo { get; set; }
    
        public virtual BileşenOranı BileşenOranı { get; set; }
        public virtual Manken Manken { get; set; }
        public virtual Tasarımcı Tasarımcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÜrünBeden> ÜrünBeden { get; set; }
        public virtual ÜrünTürü ÜrünTürü { get; set; }
    }
}
