//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ürünler
    {
        public int ürünID { get; set; }
        public string ürünAdı { get; set; }
        public Nullable<int> stokMiktarı { get; set; }
        public string bedenAdı { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<decimal> boy { get; set; }
        public Nullable<decimal> kilo { get; set; }
    }
}
