//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÜrünBeden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ÜrünBeden()
        {
            this.Sipariş = new HashSet<Sipariş>();
        }
    
        public int ürünBedenID { get; set; }
        public int BedenID { get; set; }
        public Nullable<int> ürünID { get; set; }
        public Nullable<int> stokMiktarı { get; set; }
    
        public virtual Beden Beden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipariş> Sipariş { get; set; }
        public virtual Ürün Ürün { get; set; }
    }
}
